---
# This workflow triggers on pull requests and pushes to the main branch.
# It uses Packer at latest version to init, validate and build
# an example configuration in a folder.
# This action is compatible with Packer v1.7.0 or later.
name: build

on:
  push:
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
    branches:
      - main
  pull_request:
    paths:
      - "go.mod"
      - "go.sum"
      - "**.go"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: validate
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '^1.20.2'

      - name: Build plugin
        run: go build
